name: LineFormatter

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
    - name: nuget restore
      run: nuget restore LineFormatter.sln 
    - name: build
      run: MSBuild.exe /p:Configuration=Release /p:Platform="Any CPU" LineFormatter.sln

